
"""SA_education.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fXs95T26_TMUX4qdoBlmzJmhBAmUDFQM
"""

import pandas as pd

# Load the CSV
df = pd.read_csv('education_zaf (1).csv')

# Inspect the data
print(df.shape)
df.head()

# 1. Rename columns
df.columns = ['country', 'iso3', 'year', 'indicator_name', 'indicator_code', 'value']

# 2. Drop rows where year is missing
df = df.dropna(subset=['year'])

# 3. Now convert year to integer
df['year'] = df['year'].astype(int)

# 4. Drop rows where value is missing (if any)
df = df.dropna(subset=['value'])

# 5. Remove duplicates
df = df.drop_duplicates()

# 6. Check the result
print("Cleaned shape:", df.shape)
df.head()

# List of indicator codes we'll use
selected_codes = [
    # Attainment (Barro-Lee)
    'BAR.NOED.1519.FE.ZS', 'BAR.NOED.1519.ZS',
    'BAR.PRM.CMPT.1519.FE.ZS', 'BAR.PRM.CMPT.1519.ZS',
    'BAR.SEC.CMPT.2024.FE.ZS', 'BAR.SEC.CMPT.2024.ZS',
    'BAR.TER.CMPT.25UP.FE.ZS', 'BAR.TER.CMPT.25UP.ZS',

    # Enrolment and efficiency
    'SE.PRM.ENRR', 'SE.SEC.ENRR', 'SE.TER.ENRR',
    'SE.PRM.UNER.ZS', 'SE.SEC.UNER.LO.ZS',
    'SE.PRM.REPT.ZS', 'SE.SEC.REPT.ZS',

    # Learning outcomes
    'LO.PIRLS.REA', 'LO.TIMSS.MAT4', 'LO.TIMSS.MAT8',
    'LO.PIRLS.REA.LOW', 'LO.PIRLS.REA.INT', 'LO.PIRLS.REA.HI',

    # Finance
    'SE.XPD.TOTL.GD.ZS',

    # Demographics
    'SP.POP.1524.TO.UN'
]

# Filter the dataframe
df_filtered = df[df['indicator_code'].isin(selected_codes)].copy()

# Check results
print("Filtered shape:", df_filtered.shape)
print("Unique indicators:", df_filtered['indicator_code'].nunique())
print("\nIndicators in filtered data:")
print(df_filtered['indicator_code'].unique())

# Pivot the data: each indicator becomes a column
df_pivot = df_filtered.pivot_table(
    index='year',
    columns='indicator_code',
    values='value'
).reset_index()

# Reset column names (flatten the multi-index)
df_pivot.columns.name = None

# View the result
print("Pivoted shape:", df_pivot.shape)
df_pivot.head()

import matplotlib.pyplot as plt
import seaborn as sns

# Set style
sns.set_style("whitegrid")

# Create a figure with multiple subplots
fig, axes = plt.subplots(2, 2, figsize=(14, 10))
fig.suptitle('Educational Trends in South Africa', fontsize=16)

# 1. Percentage with no education (age 15-19)
axes[0,0].plot(df_pivot['year'], df_pivot['BAR.NOED.1519.ZS'], marker='o', label='Total')
axes[0,0].plot(df_pivot['year'], df_pivot['BAR.NOED.1519.FE.ZS'], marker='s', label='Female')
axes[0,0].set_title('No Education (Age 15-19)')
axes[0,0].set_xlabel('Year')
axes[0,0].set_ylabel('Percentage')
axes[0,0].legend()
axes[0,0].grid(True)

# 2. Primary completion (age 15-19)
axes[0,1].plot(df_pivot['year'], df_pivot['BAR.PRM.CMPT.1519.ZS'], marker='o', label='Total')
axes[0,1].plot(df_pivot['year'], df_pivot['BAR.PRM.CMPT.1519.FE.ZS'], marker='s', label='Female')
axes[0,1].set_title('Completed Primary (Age 15-19)')
axes[0,1].set_xlabel('Year')
axes[0,1].set_ylabel('Percentage')
axes[0,1].legend()
axes[0,1].grid(True)

# 3. Secondary completion (age 20-24)
axes[1,0].plot(df_pivot['year'], df_pivot['BAR.SEC.CMPT.2024.ZS'], marker='o', label='Total')
axes[1,0].plot(df_pivot['year'], df_pivot['BAR.SEC.CMPT.2024.FE.ZS'], marker='s', label='Female')
axes[1,0].set_title('Completed Secondary (Age 20-24)')
axes[1,0].set_xlabel('Year')
axes[1,0].set_ylabel('Percentage')
axes[1,0].legend()
axes[1,0].grid(True)

# 4. Tertiary completion (age 25+)
axes[1,1].plot(df_pivot['year'], df_pivot['BAR.TER.CMPT.25UP.ZS'], marker='o', label='Total')
axes[1,1].plot(df_pivot['year'], df_pivot['BAR.TER.CMPT.25UP.FE.ZS'], marker='s', label='Female')
axes[1,1].set_title('Completed Tertiary (Age 25+)')
axes[1,1].set_xlabel('Year')
axes[1,1].set_ylabel('Percentage')
axes[1,1].legend()
axes[1,1].grid(True)

plt.tight_layout()
plt.show()

# Check data types
print(df_pivot.dtypes)

# Check for any extreme values
print("\nSummary statistics:")
df_pivot.describe()

# Check which years have data for secondary and tertiary
print("\nSecondary completion data (age 20-24):")
print(df_pivot[['year', 'BAR.SEC.CMPT.2024.ZS']].dropna())

print("\nTertiary completion data (age 25+):")
print(df_pivot[['year', 'BAR.TER.CMPT.25UP.ZS']].dropna())

import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("whitegrid")

fig, axes = plt.subplots(2, 2, figsize=(14, 10))
fig.suptitle('Educational Trends in South Africa', fontsize=16)

# No Education (Age 15-19)
axes[0,0].plot(df_pivot['year'], df_pivot['BAR.NOED.1519.ZS'], marker='o', label='Total')
axes[0,0].plot(df_pivot['year'], df_pivot['BAR.NOED.1519.FE.ZS'], marker='s', label='Female')
axes[0,0].set_title('No Education (Age 15-19)')
axes[0,0].set_xlabel('Year')
axes[0,0].set_ylabel('Percentage')
axes[0,0].legend()
axes[0,0].grid(True)

# Completed Primary (Age 15-19)
axes[0,1].plot(df_pivot['year'], df_pivot['BAR.PRM.CMPT.1519.ZS'], marker='o', label='Total')
axes[0,1].plot(df_pivot['year'], df_pivot['BAR.PRM.CMPT.1519.FE.ZS'], marker='s', label='Female')
axes[0,1].set_title('Completed Primary (Age 15-19)')
axes[0,1].set_xlabel('Year')
axes[0,1].set_ylabel('Percentage')
axes[0,1].legend()
axes[0,1].grid(True)

# Completed Secondary (Age 20-24)
axes[1,0].plot(df_pivot['year'], df_pivot['BAR.SEC.CMPT.2024.ZS'], marker='o', label='Total')
axes[1,0].plot(df_pivot['year'], df_pivot['BAR.SEC.CMPT.2024.FE.ZS'], marker='s', label='Female')
axes[1,0].set_title('Completed Secondary (Age 20-24)')
axes[1,0].set_xlabel('Year')
axes[1,0].set_ylabel('Percentage')
axes[1,0].legend()
axes[1,0].grid(True)

# Completed Tertiary (Age 25+)
axes[1,1].plot(df_pivot['year'], df_pivot['BAR.TER.CMPT.25UP.ZS'], marker='o', label='Total')
axes[1,1].plot(df_pivot['year'], df_pivot['BAR.TER.CMPT.25UP.FE.ZS'], marker='s', label='Female')
axes[1,1].set_title('Completed Tertiary (Age 25+)')
axes[1,1].set_xlabel('Year')
axes[1,1].set_ylabel('Percentage')
axes[1,1].legend()
axes[1,1].grid(True)

plt.tight_layout()
plt.show()

# Calculate Gender Parity Index for each indicator
df_pivot['GPI_NOED_1519'] = df_pivot['BAR.NOED.1519.FE.ZS'] / df_pivot['BAR.NOED.1519.ZS']
df_pivot['GPI_PRM_1519'] = df_pivot['BAR.PRM.CMPT.1519.FE.ZS'] / df_pivot['BAR.PRM.CMPT.1519.ZS']
df_pivot['GPI_SEC_2024'] = df_pivot['BAR.SEC.CMPT.2024.FE.ZS'] / df_pivot['BAR.SEC.CMPT.2024.ZS']
df_pivot['GPI_TER_25UP'] = df_pivot['BAR.TER.CMPT.25UP.FE.ZS'] / df_pivot['BAR.TER.CMPT.25UP.ZS']

# Plot GPI trends
fig, axes = plt.subplots(2, 2, figsize=(14, 10))
fig.suptitle('Gender Parity Index (GPI) Trends in South Africa', fontsize=16)

# No Education GPI
axes[0,0].plot(df_pivot['year'], df_pivot['GPI_NOED_1519'], marker='o', color='purple')
axes[0,0].axhline(y=1.0, color='red', linestyle='--', alpha=0.5)
axes[0,0].set_title('No Education (Age 15-19) - GPI')
axes[0,0].set_xlabel('Year')
axes[0,0].set_ylabel('GPI (Female/Total)')
axes[0,0].grid(True)

# Primary GPI
axes[0,1].plot(df_pivot['year'], df_pivot['GPI_PRM_1519'], marker='o', color='purple')
axes[0,1].axhline(y=1.0, color='red', linestyle='--', alpha=0.5)
axes[0,1].set_title('Completed Primary (Age 15-19) - GPI')
axes[0,1].set_xlabel('Year')
axes[0,1].set_ylabel('GPI (Female/Total)')
axes[0,1].grid(True)

# Secondary GPI
axes[1,0].plot(df_pivot['year'], df_pivot['GPI_SEC_2024'], marker='o', color='purple')
axes[1,0].axhline(y=1.0, color='red', linestyle='--', alpha=0.5)
axes[1,0].set_title('Completed Secondary (Age 20-24) - GPI')
axes[1,0].set_xlabel('Year')
axes[1,0].set_ylabel('GPI (Female/Total)')
axes[1,0].grid(True)

# Tertiary GPI
axes[1,1].plot(df_pivot['year'], df_pivot['GPI_TER_25UP'], marker='o', color='purple')
axes[1,1].axhline(y=1.0, color='red', linestyle='--', alpha=0.5)
axes[1,1].set_title('Completed Tertiary (Age 25+) - GPI')
axes[1,1].set_xlabel('Year')
axes[1,1].set_ylabel('GPI (Female/Total)')
axes[1,1].grid(True)

plt.tight_layout()
plt.show()

# Display the GPI columns
print(df_pivot[['year', 'GPI_NOED_1519', 'GPI_PRM_1519', 'GPI_SEC_2024', 'GPI_TER_25UP']])

# Show non‑NaN GPI values
print(df_pivot[df_pivot['GPI_SEC_2024'].notna()][['year', 'GPI_SEC_2024']])

# Save the pivoted data (including GPI columns) to CSV
df_pivot.to_csv('education_final.csv', index=False)

# Download to my computer
from google.colab import files
files.download('education_final.csv')

# Save the pivoted data (including GPI columns) to CSV
df_pivot.to_csv('education_final.csv', index=False)

# Download to my computer
from google.colab import files
files.download('education_final.csv')

# @title
